; PlatformIO Project Configuration File
;
; Carrinho ESP32-C3
; Arduino-ESP32 3.x via pioarduino
;
; Esta configuração permite usar a API LEDC nova:
;   ledcAttach(pin, freq, resolution)
;   ledcWrite(pin, duty)

[env:esp32-c3-devkitm-1]

; Plataforma comunitária pioarduino
; baseada no Arduino-ESP32 3.x
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.35/platform-espressif32.zip

board = esp32-c3-devkitm-1
framework = arduino

; Monitor Serial
monitor_speed = 115200

; USB nativa do ESP32-C3
build_flags =
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; Bibliotecas
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.0
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14