; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c3-devkitm-1]
; ⚠️ ADICIONADO @ ^6.7.0 PARA ATUALIZAR O DRIVER DO PWM DO ESP32-C3
platform = espressif32 @ ^6.7.0
board = esp32-c3-devkitm-1
framework = arduino

; Velocidade do Monitor Serial
monitor_speed = 115200

; Ativa a USB nativa do ESP32-C3 de forma correta
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1

; 📚 AQUI FICAM AS SUAS BIBLIOTECAS (O PlatformIO baixa sozinho!)
lib_deps =
    madhephaestus/ESP32Servo @ ^3.0.0
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
